// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeSnippets: typeof import('./components/ccp/code-snippets.md')['default']
    Definitions: typeof import('./components/ccp/definitions.md')['default']
    Erlang: typeof import('./components/ccp/erlang.md')['default']
    KeyTerms: typeof import('./components/ccp/key-terms.md')['default']
    Misc: typeof import('./components/ccp/misc.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
